// Jeu d'icônes de l'interface (Lucide). Les plugins désignent leurs icônes par ces noms.
import {
  ArrowLeftRight,
  Bolt,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cone,
  Copy,
  CornerDownRight,
  Cylinder,
  FileText,
  Flame,
  Gauge,
  Hammer,
  House,
  Keyboard,
  Layers,
  LayoutGrid,
  Minus,
  Palette,
  PanelLeft,
  Plus,
  Puzzle,
  RefreshCw,
  Search,
  Settings,
  Shapes,
  Sigma,
  Spline,
  Square,
  Star,
  Triangle,
  TriangleRight,
  Weight,
  X,
  Zap,
} from "@lucide/svelte";

export const ICONS = {
  home: House,
  sigma: Sigma,
  layers: Layers,
  hammer: Hammer,
  weight: Weight,
  flame: Flame,
  "triangle-right": TriangleRight,
  triangle: Triangle,
  spline: Spline,
  arrows: ArrowLeftRight,
  cylinder: Cylinder,
  grid: LayoutGrid,
  shapes: Shapes,
  bend: CornerDownRight,
  vee: ChevronDown,
  bolt: Bolt,
  gauge: Gauge,
  cone: Cone,
  zap: Zap,
  panel: PanelLeft,
  settings: Settings,
  search: Search,
  x: X,
  plus: Plus,
  back: ChevronLeft,
  next: ChevronRight,
  minus: Minus,
  square: Square,
  copy: Copy,
  star: Star,
  puzzle: Puzzle,
  clock: Clock,
  file: FileText,
  palette: Palette,
  refresh: RefreshCw,
  keyboard: Keyboard,
};

export type IconName = keyof typeof ICONS;
